[package]
name = "ipccord"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
anyhow = { version = "1.0.86" }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = { version = "1.0.125" }
thiserror = { version = "1.0.63" }
