name: Rust CI - Build and test project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build project
        run: cargo build --verbose

      - name: Run tests 
        run: cargo test --verbose
